<a href="https://colab.research.google.com/github/Oneness-Company/Oneness-Company2/blob/main/Qlearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as nm

In [ ]:

 R = nm.matrix([
     [-1,-1,-1,-1, 0,-1],
     [-1,-1,-1,0,-1,100],
     [-1,-1,-1,0,-1,-1],
     [-1,0,0,-1,0,-1],
     [-1,0,0,-1,-1,100],
     [-1,0,-1,-1,0,100]])



In [ ]:
Q = nm.matrix(nm.zeros([6,6]))

In [ ]:
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
gamma = 0.8
intial_state = 1

In [ ]:
def available_actions(state):
  current_state_row = R[state,]
  av_act = nm.where(current_state_row >=0)[1]
  return av_act

In [ ]:
available_act = available_actions(intial_state)
print(available_act)

[3 5]


In [ ]:
def sample_next_action(available_act):
  next_action = int(nm.random.choice(available_act,1))
  return next_action

In [ ]:
action = sample_next_action(available_act)
print(action)

5


<ipython-input-9-b8845f5599c3>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  next_action = int(nm.random.choice(available_act,1))


In [ ]:
def update(current_state,action,gamma):
  max_index = nm.where(Q[action,]==nm.max(Q[action,]))[1]
  if max_index.shape[0]>1:
    max_index = int(nm.random.choice(max_index,size = 1))
  else:
    max_index = int(max_index)
  max_value = Q[action,max_index]
  Q[current_state,action] = R[current_state,action] + gamma * max_value



In [ ]:
for i in range(10000):
  current_state = nm.random.randint(0,int(Q.shape[0]))
  available_act = available_actions(current_state)
  action = sample_next_action(available_act)
  update(current_state,action,gamma)

<ipython-input-9-b8845f5599c3>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  next_action = int(nm.random.choice(available_act,1))
<ipython-input-13-c883ffe5c87a>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  max_index = int(nm.random.choice(max_index,size = 1))
<ipython-input-13-c883ffe5c87a>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  max_index = int(max_index)


In [ ]:
print(Q)

[[  0.   0.   0.   0. 400.   0.]
 [  0.   0.   0. 320.  -1. 500.]
 [  0.   0.   0. 320.   0.   0.]
 [  0. 400. 256.   0. 400.   0.]
 [  0. 400. 256.   0.   0. 500.]
 [  0. 400.   0.   0. 400. 500.]]


In [ ]:
print(Q/nm.max(Q)*100)

[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.   -0.2 100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [  0.   80.   51.2   0.    0.  100. ]
 [  0.   80.    0.    0.   80.  100. ]]


In [ ]:
current_state = 2
steps = [current_state]

In [31]:
while current_state !=5:
  next_step_index = nm.where(Q[current_state,]==nm.max(Q[current_state,]))[1]
  if next_step_index.shape[0]>1:
    next_step_index = int(nm.random.choice(next_step_index,size = 1))

  else:
    next_step_index = int(next_step_index)
  steps.append(next_step_index)
  current_state = next_step_index
print(steps)

[2, 3, 4, 5]


In [ ]:
print("path: ",steps)

path:  [2]
